const List<Map<String, dynamic>> animalData = [
  {
    "id": "1",
    "name": "Buddy",
    "breed": "Golden Retriever",
    "age": 3,
    "imageUrl": "",
    "type": "dog",
  },
  {
    "id": "2",
    "name": "Whiskers",
    "breed": "Siamese",
    "age": 3,
    "imageUrl": "",
    "type": "cat",
  },
  {
    "id": "3",
    "name": "Max",
    "breed": "Bulldog",
    "age": 2,
    "imageUrl": "",
    "type": "dog",
  },
  {
    "id": "4",
    "name": "Luna",
    "breed": "Persian",
    "age": 1,
    "imageUrl": "",
    "type": "cat",
  },
  {
    "id": "5",
    "name": "Charlie",
    "breed": "Beagle",
    "age": 2,
    "imageUrl": "",
    "type": "dog",
  },
  {
    "id": "6",
    "name": "Spike",
    "breed": "Iguana",
    "age": 1,
    "imageUrl": "",
    "type": "reptile",
  },
  {
    "id": "7",
    "name": "Rango",
    "breed": "Chameleon",
    "age": 3,
    "imageUrl": "",
    "type": "reptile",
  },
  {
    "id": "8",
    "name": "Tweety",
    "breed": "Canary",
    "age": 2,
    "imageUrl": "",
    "type": "bird",
  },
  {
    "id": "9",
    "name": "Polly",
    "breed": "Parrot",
    "age": 4,
    "imageUrl": "",
    "type": "bird",
  }
];
